### ISSUE TITLE
[bug] Error: unsupported network while connecting to wallet from different chain

### ISSUE THREAD

**Issue by bigint** [tmm/wagmi#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3

### Current Behavior

Throwing the error

### Expected Behavior

Better error handling

### Anything else?

![image](https://user-images.githubusercontent.com/69431456/168563159-89cd0362-c774-4748-9c78-1561e89fdcb6.png)

**Comment by bigint** [comment]
cc @tmm

**Comment by bigint** [comment]
Sentry: https://sentry.io/share/issue/4ad9ef23ca554e8d9399118d99a80d72/

**Comment by tmm** [comment]
This error happens when a ethers provider does not support the chain passed to it. In this case, chain id `42262` is not supported by the [`InfuraProvider`](https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/infura-provider.ts#L84-L125). You could check if the chain is supported and fallback to another ethers provider or default chain id.
