### ISSUE TITLE
[bug] Warning: Text content did not match. Server: "Injected (unsupported)" Client: "MetaMask"

### ISSUE THREAD

**Issue by liran319** [tmm/wagmi#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.0.17

### Current Behavior

When I clone examples/next to local, visit index page, found that MetaMask button is disabled, it seems that MetaMask in connectors is not ready, and there is another warning says 
`Warning: Text content did not match. Server: "Injected" Client: "MetaMask"
    at button`
![image](https://user-images.githubusercontent.com/4019372/148580659-8c4ae8a3-4048-4d3f-a818-8e2581ef43be.png)

So, what's the reason leads that issue?

### Expected Behavior

1. No this warning;
2. Button should not be disabled since MetaMask is installed.

**Comment by tmm** [comment]
If you want to use the InjectedConnector's `name` property in server environments (i.e. Next.js), you should [check if the component is mounted](https://github.com/tmm/wagmi/issues/28#issuecomment-1005166819).

You could also use the connector's `id` property instead of `name` since that is guaranteed to be stable.

**Comment by liran319** [comment]
Issue created from https://github.com/tmm/wagmi/discussions/46
