### ISSUE TITLE
[bug] chainId doesn't appear to work with useEnsName

### ISSUE THREAD

**Issue by hhff** [tmm/wagmi#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.8

### Current Behavior

For a component like this:
```
const Address: FC<Props> = ({
  address,
}) => {
  const { data: ensName } = useEnsName({
    address: address,
    chainId: 1
  });

  return <p>{ensName || 'Not Found'}</p>
};
```

I'm developing on Matic Mumbai, so my client looks like this:
```
const alchemyId = process.env.NEXT_PUBLIC_ALCHEMY_PROJECT_ID;
const { chains, provider, webSocketProvider } = configureChains(
  [chain.polygonMumbai],
  [alchemyProvider({ alchemyId }), publicProvider()],
);

const client = createClient({
  autoConnect: true,
  connectors: [
    new MetaMaskConnector({ chains })
  ],
  provider,
  webSocketProvider,
});
```

I get the following error:
```
next-dev.js?3515:25 Error: network does not support ENS (operation="lookupAddress", network="maticmum", code=UNSUPPORTED_OPERATION, version=providers/5.6.2)
    at Logger.makeError (index.js?dd68:219:1)
    at Logger.throwError (index.js?dd68:228:1)
    at FallbackProvider.eval (base-provider.js?e2a1:1772:1)
    at Generator.next (<anonymous>)
    at fulfilled (base-provider.js?e2a1:5:43)
```

### Expected Behavior

My understanding is that because I'm pointing to `chainId: 1` in `useEnsName` as per the [docs](https://wagmi.sh/docs/hooks/useEnsName#chainid-optional), my request to resolve from ENS should work.

If I'm misunderstanding, I'm sorry! I can submit a docs PR.
If something is broken, I can submit a code PR :)

### Anything else?

<3 WAGMI.SH RULES

**Comment by tmm** [comment]
`configureChains` currently requires that you define all chains upfront that you want to use and falls back to the first in the list if an "unknown" chain is provided. Since Mainnet (chain id 1) isn't configured, the provider falls back to Polygon Mumbai. `useEnsName` uses Polygon Mumbai which does not support ENS, thus the error. You can fix this by adding Mainnet to the list of chains configured.

There is also a small bug where `chainId` isn't passed through, which is fixed in https://github.com/tmm/wagmi/pull/555.

**Comment by hhff** [comment]
Gotcha, thank you @tmm. I did try adding mainnet to the list, but it did not work either, I'd guess due to #555.

🥳  Updated to `0.4.9` and added `[..., chain.mainnet]` and it's working! Thank you!
